package ru.habit.tracker

enum class Screens(val route: String) {
    LOGIN("LOGIN"),
    REGISTRATION("REGISTRATION"),
    RECOVERY("RECOVERY"), MAIN("MAIN"),
    NEW_PASSWORD_SCREEN("NEW_PASSWORD_SCREEN"),
    CONFIRMATION_SCREEN("CONFIRMATION_SCREEN"),
    CONGRATULATIONS_SCREEN("CONGRATULATIONS_SCREEN"),

}

